name: Build, Push & Deploy Frontend + Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Add environment.ts
        run: |
          mkdir -p frontend/src/app/core
          cat <<EOF > frontend/src/app/core/environment.ts
          export const environment = {
            apiUrl: '${{ secrets.API_URL }}',
            auth0Domain: '${{ secrets.AUTH0_DOMAIN }}',
            auth0ClientId: '${{ secrets.AUTH0_CLIENT_ID }}',
          };
          EOF

      - name: Add .env to backend
        run: |
          cat <<EOF > backend/.env
          PORT=${{ secrets.PORT }}
          MONGO_URL=${{ secrets.MONGO_URL }}
          FRONTEND=${{ secrets.FRONTEND }}
          LOCAL=${{ secrets.LOCAL }}
          ISSUER_URL=${{ secrets.ISSUER_URL }}
          API_URL=${{ secrets.API_URL_BACKEND }}
          AZURE_STORAGE_CONN_STRING=${{ secrets.AZURE_STORAGE_CONN_STRING }}
          EOF

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/synceq:backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/synceq:backend

      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/synceq:frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/synceq:frontend

      - name: Deploy Backend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: synceq-backend
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          images: docker.io/${{ secrets.DOCKER_USERNAME }}/synceq:backend

      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: synceq
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
          images: docker.io/${{ secrets.DOCKER_USERNAME }}/synceq:frontend
